---
apiVersion: v1
kind: Pod
metadata:
 name: httpd-pod
 labels:
   type: webswerver
spec:
 containers:
   - name: myhttpd
     image: httpd
     resources:
      requests: 
       memory: "64Mi"
       cpu: "250M"
      limits:
        memory: "128Mi"
        cpu: "500M"
...         
